### PR TITLE
Add Feature Request template

### PR DESCRIPTION
**Pull request by Jarmos-san**
Add a feature request template for the whole organization use and/or take inspiration from.

### CODE REVIEW

**Review by Bhupesh-V — CHANGES_REQUESTED** [review]
Can we go with YAML templates now?
https://docs.github.com/en/github-ae@latest/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

these kinds of templates are generally not respected, wdyt?

**Comment by Jarmos-san** [comment]
> these kinds of templates are generally not respected, wdyt?

Like this one #6.

My bad I should've created a single PR with all the issue templates instead of creating separate ones. Should I close these PRs & create another with all Issue Templates instead?

**Comment by Bhupesh-V** [comment]
> > these kinds of templates are generally not respected, wdyt?
> 
> Like this one #6.
> 
> My bad I should've created a single PR with all the issue templates instead of creating separate ones. Should I close these PRs & create another with all Issue Templates instead?

Yes YAML templates would be nice
We can modify each PRs no problem with that 👍🏽

**Comment by Jarmos-san** [comment]
All Issue Templates conform with the new YAML templates right now. Do let me know if there's something to be changed.

**Review by Bhupesh-V — APPROVED** [review]

**Pull request merged**
